### ISSUE TITLE
optimize connection pool and session(maker)

### ISSUE THREAD

**Issue by sgratzl** [datavisyn/tdp_core#111]
In the current version a simple to no explicit approach is used.

**Comment by sgratzl** [comment]
start in https://github.com/datavisyn/tdp_core/commit/a08bf1254af2c620367ef7185132677e427b8919

**Comment by anita-steiner** [comment]
is there also a connection pool included (http://docs.sqlalchemy.org/en/latest/core/pooling.html)

**Comment by sgratzl** [comment]
the connection pool is automatically used. In the lineupjs3 branch also the session making is centralized. closing for now
