### ISSUE TITLE
Score columns width too small

### ISSUE THREAD

**Issue by anita-steiner** [datavisyn/tdp_core#117]
develop branch

### Steps to reproduce

dtiles -> combined view

### Observed behavior
* score column width too small

![screenshot from 2018-07-18 11-31-33](https://user-images.githubusercontent.com/14962506/42872798-2a538870-8a7e-11e8-9b8e-4bc4a83f928d.png)

**Comment by sgratzl** [comment]
this view sets a width of 50px on purpose thus not a bug
