### ISSUE TITLE
Touring: New feature indicator

### ISSUE THREAD

**Issue by keckelt** [datavisyn/tdp_core#131]
Provide some visual hint that there is the new touring feature/button.

E.g.:
![image](https://user-images.githubusercontent.com/10337788/48248016-7f761700-e3ed-11e8-8358-f1521dbda978.png)

Or: https://codepen.io/wifeo/pen/KwdXwV
![peek 2018-11-09 08-08](https://user-images.githubusercontent.com/10337788/48248199-47230880-e3ee-11e8-9594-ea93bf30c3fc.gif)
+ some introduction in the panel

**Comment by keckelt** [comment]
In the touring panel, incude that: we only compare the displayed columns and rows, i.e. stufff the users removed / did not include is ignored.

**Comment by keckelt** [comment]
Examples:
Compare Selected with Categories: Select rows with mutated gene tp53 find similarities to categories in other attributes.
Compare selected with stratification groups: Select rows with mutated gene tp53 and find similarites in the groups you have defined
Pairwise compare stratification groups: Compare the rows of your generated stratification groups (is item distribution similar/different).
Pairwise Compare Categories: Mutated vs Non Mutated
Pairwise Compare Attributes: Compare Mutated non Mutated of two genes (cat-cat), compare relative copy numbers (nu,m-num), see wether cell lines with  mutated  gene XY are enriched on relative copy number of UV (cat-num)

**Comment by sgratzl** [comment]
isn't that just a tour of a ranking view?

**Comment by mstreit** [comment]
I see use for both: a 'that's new' popup that provides a concise summary and value of the new touring features. In addition, the new touring features can be presented using a tour (https://github.com/Caleydo/tdp_bi_bioinfodb/issues/513)

**Comment by keckelt** [comment]
Oh nice, didn't see that.

**Comment by keckelt** [comment]
Thomas will mention it in the release notes of the ordino version that ships with the touring feature.
