### ISSUE TITLE
Touring Sidebar - Mini Visualisation

### ISSUE THREAD

**Issue by PatrickAdelberger** [datavisyn/tdp_core#132]
- [ ] Visualisation Details
  - [x] display score & p-value
  - [ ] what is compared
  - [ ] what is the information this score gives
- [x] Parallel Sets 
  - [x] move label of 2nd dimension underneath the plot
  - [x] adjust label for small categories (currently not readable)
  - [x] only display the selected column and row
    - [x] change the 2 dimensions: 1 =[selectedRow + others] & 2 = [selectedColumn + others]
    - [x] change sizes of the used sets to the union of the 2 selected sets
  - [x] change vis for the comparison of SG with SG 
- [x] Box Plot
  - [x] colour of boxplots should be the colour of the column and higher opacity for the selected one

**Comment by keckelt** [comment]
Moved to https://github.com/Caleydo/tdp_bi_bioinfodb/issues/902
