### ISSUE TITLE
create swagger.json from view definition

### ISSUE THREAD

**Issue by sgratzl** [datavisyn/tdp_core#18]
the view definition almost contains everything needed for generating a proper swagger.json file without any dynamic things. 

missing
 * arg typings (number, string, list of number, list of strings)

**Comment by sgratzl** [comment]
generated swagger.json for tdp with the dummy plugin:

[swagger.json.txt](https://github.com/datavisyn/tdp_core/files/1793134/swagger.json.txt)

**Comment by sgratzl** [comment]
btw. https://github.com/phovea/phovea_security_flask support three ways to login
 * via a post to `/login`
 * via basic authentification
 * via `api_key` request parameter (currently implemented as `user:password`

**Comment by sluger** [comment]
:+1:

**Comment by sgratzl** [comment]
@zichner the swager feature could also be useful for you. 

after the next deployment just take a look at: `/api/tdp/ui`
