### ISSUE TITLE
Make dbview.security to a boolean value

### ISSUE THREAD

**Issue by anita-steiner** [datavisyn/tdp_core#189]
dbview.security has two types:
* string: to set groups, the user must be in, to get access
* function: a function that is called, to check, if the user has access

the third option should be a boolean value and default value should be set to True:
* if the boolean value is false, no security (also the login_required) should be checked

The following changes should be done:
* the default value for security should be set to True
* can_access in dbview.py should be changed
* canAccess in findViews should be changed
* add a new decorator function 'tdp_login_required' that checks the security and calls the login_required if necessary

**Comment by anita-steiner** [comment]
and we should document that in the wiki

**Comment by lehnerchristian** [comment]
I've documented this in the tutorial "How to create a DB connector - see https://wiki.datavisyn.io/tdp/tutorials/how-to-create-a-db-connector#security

**Comment by lehnerchristian** [comment]
so, can we close this issue?
