### ISSUE TITLE
Logo in info dialog is now huge

### ISSUE THREAD

**Issue by lehnerchristian** [datavisyn/tdp_core#246]
* Release number or git hash: 
* Web browser version and OS: 
* Environment (local or deployed): 

### Steps to reproduce

1. Open an application (e.g., see https://dtiles.app.datavisyn.io/)
2. Open the info dialog (`i` icon on the top right)

### Observed behavior
* The datavisyn icon is now huge

![grafik](https://user-images.githubusercontent.com/5851088/68946421-3d777200-07b3-11ea-9c11-2f4b074bb7a0.png)

### Expected behavior
* The icon should have a normal size

**Comment by lehnerchristian** [comment]
The old logo was already huge, so this is not a new problem

**Comment by anita-steiner** [comment]
see https://github.com/datavisyn/tdp_core/issues/274

**Comment by lehnerchristian** [comment]
closed in favor of #274
