### ISSUE TITLE
GZip server responses

### ISSUE THREAD

**Issue by keckelt** [datavisyn/tdp_core#265]
I saw that the responses by the tdp_core/phovea_server endpoints are currently not zipped:
![image](https://user-images.githubusercontent.com/10337788/70623892-5d1d8100-1c1f-11ea-8586-bc42939f6c33.png)
([Content-Encoding](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Encoding) should be set (`gzip`))

On Python3.7 i made a [short test](https://github.com/datavisyn/tdp_core/commit/c1c4b28dd9fd968695131ba1cf04f969d977fdb8) with [Flask-Compress](https://github.com/colour-science/flask-compress) which worked (90% reduction for the json):
![image](https://user-images.githubusercontent.com/10337788/70624030-a241b300-1c1f-11ea-929f-5093453b03ae.png)

**Comment by thinkh** [comment]
Just for clarification: The first screenshot is phovea_server/tdp_core with Python 2.7 and your feature request describes that the server should react to the request header and apply gzip to our response?

The second screenshot then, shows the result using Flask-Compress with Python 3.7, correct? 

If we decide to use Flask-Compess, we should perform further testing if it works in all browser and all content types (JSON, HTML, ...). We will do this once you file a PR.

**Comment by thinkh** [comment]
An alternative to Flask-Compress and gzip would be the [Brotli](https://tools.ietf.org/html/rfc7932) as compression algorithm, which is [well supported by the browsers](https://caniuse.com/#search=brotli) and has a stronger compression. If we decide for Brotli we need to find the right Brotli compression level, which is a trade-off between CPU load and file size (i.e., compression ratio).

Very recent implementation for JS/CSS files (only?) would be [Flask-Squeeze](https://pypi.org/project/Flask-Squeeze/). Otherwise we can use the Brotli [Python library](https://github.com/google/brotli). See also [this tutorial](https://techtutorialsx.com/2018/12/05/python-brotli-compression/).

**Comment by keckelt** [comment]
> Just for clarification: The first screenshot is phovea_server/tdp_core with Python 2.7 and your feature request describes that the server should react to the request header and apply gzip to our response?

Yes, but  it is  phovea_server/tdp_core with Python 3.7 (I just added/removed this line): https://github.com/datavisyn/tdp_core/commit/c1c4b28dd9fd968695131ba1cf04f969d977fdb8#diff-24662166e7f24c12c66799a3a842b29cR15


> The second screenshot then, shows the result using Flask-Compress with Python 3.7, correct? 

yes

> If we decide to use Flask-Compess, we should perform further testing if it works in all browser and all content types (JSON, HTML, ...). We will do this once you file a PR. 

Sure, it was just a quick and dirty test how it could work :)


> An alternative to Flask-Compress and gzip would be the Brotli as compression algorithm, which is well supported by the browsers and has a stronger compression.

Didn't know Brotli; nice!
I also have higher trust into Google's lib 😄

**Comment by keckelt** [comment]
Flask-Squeeze also brolti-compresses all responses, nice.

I was wondering why FF didn't accept `br`as enconding in the screenshots above: It's only used on HTTPS (see [Mozilla Hacks article](https://hacks.mozilla.org/2015/11/better-than-gzip-compression-with-brotli/) ans [Chromium Issue](https://bugs.chromium.org/p/chromium/issues/detail?id=452335#c86))

**Comment by thinkh** [comment]
> I was wondering why FF didn't accept bras enconding in the screenshots above: It's only used on HTTPS (see Mozilla Hacks article ans Chromium Issue)

That means that we cannot test brotli compression locally, but it would be available in the deployed version, right?

**Comment by keckelt** [comment]
Correct.
A fallback to gzip if br is not available would be perfect, imo.

**Comment by sgratzl** [comment]
in a deployed version shouldn't the NGINX proxying the server already handle the compression? at least that was the original idea.

**Comment by keckelt** [comment]
True; it is gzipped
![image](https://user-images.githubusercontent.com/10337788/71876903-28bab900-3128-11ea-959c-92c015b5645d.png)

**Comment by keckelt** [comment]
Does that mean the phovea_landing_page's nginx zips the response?

**Comment by thinkh** [comment]
No it's the nginx that is configured in your frontend/app (e.g., ordino_public). 

See 
[nginx-default.conf](https://github.com/Caleydo/ordino_public/blob/064090e26b28e9df28e43f821a2bf8494fd96191/deploy/nginx-default.conf#L65-L69)

```
gzip on;
gzip_proxied no_etag;
gzip_types text/plain text/comma-separated-values image/svg+xml text/xml text/css application/x-javascript application/javascript application/xml  application/xml+rss text/csv application/json text/javascript application/xhtml+xml;
gzip_vary on;
gzip_disable "MSIE [1-6]\.(?!.*SV1)";
```

@keckelt Can we close this issue then or is there something left to do?

**Comment by keckelt** [comment]
Yes :)
