### ISSUE TITLE
ideas for an icon?

### ISSUE THREAD

**Issue by sgratzl** [datavisyn/tdp_core#27]
favicon + loading icon

such that we can avoid the Caleydo Icon

**Comment by mstreit** [comment]
how about the datavisyn D? or should it be app specific (bob, ordino)?

**Comment by sgratzl** [comment]
I would prefer a logo for TDP that is independent of datavisyn. datavisyn is the company, TDP is the product.

**Comment by alexsb** [comment]
I think the d is fine, or just a generic loading circle.

**Comment by mstreit** [comment]
For now, just use the datavisyn d. Later on, when we hire a designer to take care of a corporate design, we can revisit this issue.

**Comment by mstreit** [comment]
I think we should rounded corners in the d favicon and logo.

![image](https://user-images.githubusercontent.com/4129755/32568757-7b512b4a-c4bf-11e7-88d3-13cba1d88f18.png)

**Comment by mstreit** [comment]
Latest version is fine for now:
![image](https://user-images.githubusercontent.com/4129755/36563434-565aed5e-181a-11e8-8f1a-92c76fde7437.png)

**Comment by sgratzl** [comment]
what has dTiles to do with the TDP itself, like we also don't have an icon for Ordino

**Comment by sgratzl** [comment]
can also be a task for the designer to create a logo for dTiles, Ordino, and TDP in general

**Comment by sgratzl** [comment]
won't fix
