### ISSUE TITLE
Lineup 4 Integration

### ISSUE THREAD

**Issue by anita-steiner** [datavisyn/tdp_core#275]
The following problems occurs with lineup4 (tested with patentbay):
- [x] Add Column not possible; List of Columns not in foreground
- [x] Enable/Disable Overview, Does not work with high number of patents
- [x] Title column not in line with other colums; Text is to placed high in row
- [x] Interval in header always from 0 to 0; no filtering possible

**Comment by thinkh** [comment]
@anita-steiner Were these bugs already solved? Can we close this issue?
