### ISSUE TITLE
Combined View: paramters in persisted session not tracked

### ISSUE THREAD

**Issue by lehnerchristian** [datavisyn/tdp_core#29]
* Release number or git hash: 
* Web browser version and OS: 
* Environment (local or deployed): local

### Steps to reproduce

1. Select a gene set
2. Select e.g. 2 genes
3. Open the Combined View
4. Choose a Data Subtype (columns will be added)
5. Persist session and open in another browser or private tab

### Observed behavior
* In a persisted session: All steps are reproduced, except step 4 (no subtypes are chosen and therefore no columns)
* In a temporary session: the subtypes are preserved, therefore columns are added

### Expected behavior
* The persisted session should behave like the temporary one and track the parameters of Select2

**Comment by sgratzl** [comment]
see also #32

**Comment by sgratzl** [comment]
please test again

**Comment by lehnerchristian** [comment]
tested and it works
