### ISSUE TITLE
Add Column Dialog in LineUp shows overlapping entries

### ISSUE THREAD

**Issue by puehringer** [datavisyn/tdp_core#330]
* Release number or git hash: v9
* Web browser version and OS: 
* Environment (local or deployed): 

### Steps to reproduce

1. Insert many columns into a ranking
2. Use the Sidepanel in 'top' mode (the issue might appear in normal mode too!)

### Observed behavior
The entries are overlapping due to the `max-height` restriction in https://github.com/datavisyn/tdp_core/blob/master/src/styles/_view_lineup.scss#L366. One (untested) solution might be to remove this rule altogether as the actual dialog is properly overflowing.

![image](https://user-images.githubusercontent.com/51900829/77442618-d2861980-6dea-11ea-80f5-e5a65b71e7a7.png)

### Expected behavior
* No overlapping entries with only the scrollbar of the full dialog visible (no subscrolling).

**Comment by thinkh** [comment]
Fixed with the last commit https://github.com/datavisyn/tdp_core/commit/b5fc87f8ef3f3f139811c1b2c76f50efc306cfe5.

![grafik](https://user-images.githubusercontent.com/5851088/77538096-729d7a80-6e9f-11ea-8276-25c71d821ff8.png)
