### ISSUE TITLE
LineUp 4: Collapsed groups are larger in overview mode than in normal mode

### ISSUE THREAD

**Issue by thinkh** [datavisyn/tdp_core#365]
* Release number or git hash: master, develop, and lineupjs4
* Web browser version and OS: Chrome 81
* Environment (local or deployed): both

### Steps to reproduce

1. Open https://ordino-daily.caleydoapp.org/
1. Open list of all cell lines
2. Group/stratify by tumor type
3. Collapse groups
4. Activate overview mode

### Observed behavior

**Grouping in normal mode**

![grafik](https://user-images.githubusercontent.com/5851088/81787360-341c5780-9501-11ea-8364-57f684b73bf7.png)

**Grouing in overview mode**

![grafik](https://user-images.githubusercontent.com/5851088/81787397-47c7be00-9501-11ea-8d3e-aad36c390fc3.png)

-> The collapsed groups take more space than in normal mode. This is unintuitive since the aim of the overview mode is to get as much information as possible on the screen. 

### Expected behavior

The collapsed rows should be the same size or smaller in overview mode.

### Side note

In the LineUp 4 demo the group height is consistent indepent of the overview mode.

![grafik](https://user-images.githubusercontent.com/5851088/81787504-75146c00-9501-11ea-8be6-90ab1787cb11.png)

![grafik](https://user-images.githubusercontent.com/5851088/81787535-7fcf0100-9501-11ea-8127-fb541a8f9a66.png)

**Comment by thinkh** [comment]
The investigation shows that we override/set a different group height in tdp_core.

The default group height from LineUp is [40 pixel](https://github.com/lineupjs/lineupjs/blob/4976c18e6ddc549217a9700e63a963fbce12416c/src/config.ts#L139-L143).

We override/set this value in the LineUpPanelActions with 70 pixel for the overview mode.

https://github.com/datavisyn/tdp_core/blob/e5d204e6746c707e3657d478bd2cee6e12fb1524/src/lineup/internal/LineUpPanelActions.ts#L30-L34

Furthermore, I found another value of 70 pixel if the `itemRowHeight` option in `ARankingView` is a function.

https://github.com/datavisyn/tdp_core/blob/e787860ceab37456ea334487f4147a540208b098/src/lineup/ARankingView.ts#L276-L287

We should refactor this and use the LineUp default value of 40 pixel for the group height.

**Comment by mstreit** [comment]
That's a very useful improvement, thanks.
