### ISSUE TITLE
Hierarchy for Database Columns in Add Column Dialog

### ISSUE THREAD

**Issue by puehringer** [datavisyn/tdp_core#371]
Currently, all columns are added alphabetically to the **Add Column** dialog under **Database Columns**. 
When having many columns, this gets cluttered very quickly. A solution would be a _grouping_ feature, where columns can be grouped together within a parent (similar to how detail views are grouped).  

**Example:**
There has to be a new field which indicates the parent (here `Group A` and `Group B`), such that the dialog would group columns 1 to 3 in Group A, and columns 4 and 5 in Group B: 

> **Database Columns**
> **_Group A_**
> Column 1
> Column 2
> Column 3
> **_Group B_**
> Column 4
> Column 5

This is only a feature request, the implementation details are completely open and still need to be discussed.

**Comment by mstreit** [comment]
@PatrickAdelberger implemented something similar for the new Coral Visual Cohort Analysis application that is created as part of the research collaboration with BI. I am sure he is happy to provide details if needed.

![image](https://user-images.githubusercontent.com/4129755/83752188-63d5ff80-a668-11ea-9744-1b519c92251b.png)
