### ISSUE TITLE
Change of Group By settings for string column is not persisted in the provenance graph

### ISSUE THREAD

**Issue by thinkh** [datavisyn/tdp_core#379]
* Release number or git hash: https://github.com/datavisyn/tdp_core/commit/388c3b59fec1d2dc888ce16b70fb2299ae03a3d7
* Web browser version and OS: Chrome 83
* Environment (local or deployed): both

### Steps to reproduce

1. Open https://ordino-daily.caleydoapp.org/
2. Open list of all cell lines
3. Name -> Group By
   * Text starts with …: `A`
4. Confirm dialog
5. Open Group By dialog again
   * Switch to regular expression: `^A`
6. Confirm dialog
5. Open Group By dialog again
   * Switch to by name
6. Confirm dialog

### Observed behavior

![ordino-group-by-session](https://user-images.githubusercontent.com/5851088/84902015-89252d80-b0ac-11ea-8c5e-5b2bbebf75ba.gif)

All the changes are applied correctly to ranking, but they are not stored as new state in the provenance graph. Hence, when replaying it we will not get the correct state that the user has seen before.

### Expected behavior

Switch the group by from starts with to regular expression should be stored in the provenance graph as new state.

### Implementation pointers

Similar to the filters (see #345) there must be some bug in the LineUp cmd.ts.

**Comment by thinkh** [comment]
Please note that the Group By dialog might change slightly after PR ttps://github.com/lineupjs/lineupjs/pull/352. I tested it with the current LineUp v4.0.0 version and after this PR and in both cases we are missing new provenance states.

**Comment by oltionchampari** [comment]
The problem here is that **LineUp** itself does not fire the event `Ranking.EVENT_GROUP_CRITERIA_CHANGED` when the `Group By` dialog's parameters change.

**Comment by thinkh** [comment]
According to Sam we are listening to the wrong criteria for this specific case (see https://github.com/lineupjs/lineupjs/issues/354#issuecomment-647964841):

> why should this event be fired, the group criteria order hasn't changed? it is still a StringColumn. However, the grouping itself changes, and it will fire a corresponding `dirtyOrder` event with the reason `group_dirty` and the `StringColumn` fires `groupingChanged`.

In my opinion we need to change our implementation in a way that we add a `groupingChanged` listener once the `Ranking.EVENT_GROUP_CRITERIA_CHANGED` is fired. Alternatively, we can also add this listener directly when the column is added to the column (or the ranking is initialized). In both cases we must make sure to remove the `groupingChanged` event listener if the column is removed from the ranking or/and when it is not part of the columns in  `Ranking.EVENT_GROUP_CRITERIA_CHANGED`.

@oltionchampari Can you please have a look again and see if you can implement the additional event listener?

**Comment by oltionchampari** [comment]
> According to Sam we are listening to the wrong criteria for this specific case (see [lineupjs/lineupjs#354 (comment)](https://github.com/lineupjs/lineupjs/issues/354#issuecomment-647964841)):
> 
> > why should this event be fired, the group criteria order hasn't changed? it is still a StringColumn. However, the grouping itself changes, and it will fire a corresponding `dirtyOrder` event with the reason `group_dirty` and the `StringColumn` fires `groupingChanged`.
> 
> In my opinion we need to change our implementation in a way that we add a `groupingChanged` listener once the `Ranking.EVENT_GROUP_CRITERIA_CHANGED` is fired. Alternatively, we can also add this listener directly when the column is added to the column (or the ranking is initialized). In both cases we must make sure to remove the `groupingChanged` event listener if the column is removed from the ranking or/and when it is not part of the columns in `Ranking.EVENT_GROUP_CRITERIA_CHANGED`.
> 
> @oltionchampari Can you please have a look again and see if you can implement the additional event listener?

@thinkh In that case do you think we would need another provenance action, e.g., `Group changed`?

**Comment by thinkh** [comment]
Yes, looks like this. You can name it `columnGroupingChanged` or similar.

The `groupingChanged` event is available on the following columns:

* [`StringColumn.EVENT_GROUPING_CHANGED`](https://github.com/lineupjs/lineupjs/blob/ef7ca51d3bf3022f3c63827f046a2036c9cce47d/src/model/StringColumn.ts#L70)
* [`NumberColumn.EVENT_GROUPING_CHANGED`](https://github.com/lineupjs/lineupjs/blob/89d4af69c7380f375607186b00e1b32889c74940/src/model/NumberColumn.ts#L64)
* [`DateColumn.EVENT_GROUPING_CHANGED`](https://github.com/lineupjs/lineupjs/blob/89d4af69c7380f375607186b00e1b32889c74940/src/model/DateColumn.ts#L34)

**Comment by oltionchampari** [comment]
> Yes, looks like this. You can name it `columnGroupingChanged` or similar.
> 
> The `groupingChanged` event is available on the following columns:
> 
> * [`StringColumn.EVENT_GROUPING_CHANGED`](https://github.com/lineupjs/lineupjs/blob/ef7ca51d3bf3022f3c63827f046a2036c9cce47d/src/model/StringColumn.ts#L70)
> * [`NumberColumn.EVENT_GROUPING_CHANGED`](https://github.com/lineupjs/lineupjs/blob/89d4af69c7380f375607186b00e1b32889c74940/src/model/NumberColumn.ts#L64)
> * [`DateColumn.EVENT_GROUPING_CHANGED`](https://github.com/lineupjs/lineupjs/blob/89d4af69c7380f375607186b00e1b32889c74940/src/model/DateColumn.ts#L34)

Since it is a column property, i think we should call the event `Set Property Grouping` and reuse the `recordPropertyChange()` function. @thinkh What do you think?

**Comment by thinkh** [comment]
Yes, sounds like a good idea. You can try it and test if everything works as expected.
