### ISSUE TITLE
Make a ARankingView compatible with LineUp's `IndicesArray` and `UIntTypedArray` for ordered indicies

### ISSUE THREAD

**Issue by oltionchampari** [datavisyn/tdp_core#412]
Release number or git hash: develop

Since `LineUp 4` the method `Ranking.getOrder()` and possibly others return a `Uint16Array` (which is of type object) instead of an array. This means that all the checks with `Array.isArray()` which used to return  `true` , return now `false`.
So far i have found two places where this occurs resulting in different bugs:

https://github.com/datavisyn/tdp_core/blob/b0970d3662c29d2ae5aba1729638548d5a12de8d/src/lineup/ARankingView.ts#L358-L363

https://github.com/datavisyn/tdp_core/blob/b0970d3662c29d2ae5aba1729638548d5a12de8d/src/lineup/ARankingView.ts#L380

**Comment by thinkh** [comment]
I also checked the LineUp code and saw that the [order is an `IndicesArray`](https://github.com/lineupjs/lineupjs/blob/89d3e8a2d241e2a10d2a24f0ecc6bb5ae0e2329b/src/model/interfaces.ts#L163-L167) which can be `UIntTypedArray` and `ArrayLike`

```ts
export declare type IndicesArray = (ReadonlyArray<number> | UIntTypedArray) & ArrayLike<number>;

export interface IOrderedGroup extends IGroup {
  order: IndicesArray;
}
```


The `UIntTypedArray` resolves to the [following types](https://github.com/lineupjs/lineupjs/blob/89d3e8a2d241e2a10d2a24f0ecc6bb5ae0e2329b/src/model/interfaces.ts#L196):

```ts
export declare type UIntTypedArray = Uint8Array | Uint16Array | Uint32Array;
```

Hence, we must also take the other types into account. The fix implemented with PR #413 does consider this, but does not consider the `ArrayLike` type.
