### ISSUE TITLE
Ranking scrolling issue

### ISSUE THREAD

**Issue by dvdanielamoitzi** [datavisyn/tdp_core#442]
### Steps to reproduce

1. open the ranking
2. scroll down
3. create a lineup filter
4. --> everything works fine
5. remove the filter
6. change the width of any column
7. scroll down
8. create a lineup filter
9. --> the ranking does not update the height, a lot of white space is left on the on the bottom
10. change the width of a column
11. --> the height gets updated again

![lineup-scrolling-issue](https://user-images.githubusercontent.com/57343176/98796251-79b3d180-240b-11eb-92d1-8cb97a6760ef.gif)

### Observed behavior
* when creating a lineup filter after changing the width of any column in the ranking the height of the ranking is not updated

**Comment by thinkh** [comment]
I was not able to reproduce this behavior with https://ordino-daily.caleydoapp.org/ (e.g., Cell Lines -> CCLE -> gender column). Could you try it again there? Maybe it is an app-specific bug that is caused by additional/surrounding CSS rules.

**Comment by puehringer** [comment]
Here is how I reproduced it in https://ordino-daily.caleydoapp.org/:
![Ordino_Bug](https://user-images.githubusercontent.com/51900829/99432444-6e314080-290c-11eb-92a8-1acf5cf1faa9.gif)
