### ISSUE TITLE
Implemented improved custom autocompletion / multi selection form element

### ISSUE THREAD

**Issue by sgratzl** [datavisyn/tdp_core#52]
Currently based on select2 with some customizations. However the customizations should be unified and normalized. In different applications like dTiles the search box is already advanced

features
 * [x] multi select support (aka tags)
 * [x] ajax / data option provider
 * [x] custom formatting support
    * result vs selection
    * last search term used
    * access to underlying DOM element
 * [x] paste support. Text should be pasted and automatically parsed. Separators: `\s;,`. 
   * split the input
   * validate the input individually and show current validation state (processing, error, success)
 * [x] drop file support - see paste support but just drop a text file into it instead
 * [ ] grouping support: instead of selecting and representing a single item, items should be supported that represent a set of items of which all will automatically selected. 
 * [x] custom data attributes in items. they need to have (id, text) but also others are optional and the objects shouldn't be modified
 * [x] easy way to get/set the currently selected items with AJAX support
 * [x] easy way to update the possible static options or change the AJAX data source. 
* [x] revise styles for e.g. invalid tags

**Comment by sluger** [comment]
closing this as the follow up datavisyn/tdp_core/issues/100 has been created.
