### ISSUE TITLE
Extract and reuse Select3 in FormSelect2

### ISSUE THREAD

**Issue by sluger** [datavisyn/tdp_core#88]
Select2 is limited as it does not support drop files and token validation.

Extract Select3 implementation from sgratzl/refactor into new branch.
- [x] Update FormSelect2 to use Select3 options
- [x] Update tdp_gene: search and validate

**Comment by sgratzl** [comment]
based on #52

**Comment by thinkh** [comment]
What is Select3? Is it a library?

**Comment by sgratzl** [comment]
nope: something I wrote on top of select2
https://github.com/datavisyn/tdp_core/blob/sluger/select3/src/form/internal/Select3.ts

**Comment by thinkh** [comment]
I had a look at it. Good job in terms of documentation and cleanness. 👍

**Comment by sluger** [comment]
use SearchProvider.ts in tdp_gene as base class and extract similarities (search and validate). occurrences of tdpLookupUrl which used the old ajax based select2 implementation have to be refactored

**Comment by sluger** [comment]
please clarify with me the logic behind `initialValue` in Select2, see: https://github.com/datavisyn/tdp_core/blob/748621bcb7cb12e733e48e88be0cf87e04f102ff/src/form/internal/FormMap.ts#L263-L283

**Comment by sgratzl** [comment]
select2 does allow to specify a default value by creating corresponding option entries in the underlying select dom element. In the AJAX case the initial value is the only entry: Later on the id will be faked entered to simulate an imput. But cannot you just set the value using `select3.value = ...`?
