### ISSUE TITLE
Boolean query params always return true when parsed as string

### ISSUE THREAD

**Issue by sluger** [datavisyn/tdp_core#95]
* Release number or git hash: 4.0.1
* Web browser version and OS: Chrome 65
* Environment (local or deployed): local

This bug may have to be addressed in other endpoints too.

### Steps to reproduce
1. `http://localhost:9000/api/tdp/db/<db>/<view>?_return_query=false`

### Observed behavior
API request with query param: `_return_query=false` is interpreted as True in Python
1. `http://localhost:9000/api/tdp/db/<db>/<view>?_return_query=false` is `True` -> wrong
1. `http://localhost:9000/api/tdp/db/<db>/<view>?_return_query=true` is `True`-> true but wrongly interpreted
1. `http://localhost:9000/api/tdp/db/<db>/<view>?_return_query=` is `False` -> this is ok

Only in the last case the api returns actual data, whereas in the first two cases the query is returned.

### Expected behavior
* _return_query=false should return no query

### Suggested fix
Compare with the string `'true'`: 
`def _return_query():
  return True if request.args.get('_return_query') == 'true' else False`

**Comment by sgratzl** [comment]
I would suggest
```
value = '_return_query' in request.args and request.args['_return_query'].lower()[0] != 'f'
```
